// Generated by CoffeeScript 1.6.2
define(['Crafty', 'components/TweenColor'], function(Crafty, TweenColor) {
  var key;

  key = 'Highlighter';
  Crafty.c(key, {
    init: function() {
      return this.requires(TweenColor);
    },
    baseColor: function(r, g, b) {
      this._h_base = arguments.length === 1 ? r : {
        r: r,
        g: g,
        b: b
      };
      return this.rgb(this._h_base);
    },
    highColor: function(r, g, b) {
      return this._h_high = arguments.length === 1 ? r : {
        r: r,
        g: g,
        b: b
      };
    },
    highlight: function(frames) {
      if (frames == null) {
        frames = 0;
      }
      return this.tweenColor(this._h_high, frames);
    },
    unhighlight: function(frames) {
      if (frames == null) {
        frames = 0;
      }
      return this.tweenColor(this._h_base, frames);
    },
    bindHighlightMouseEvents: function() {
      this.requires('Mouse');
      this.bind('MouseOver', this.mouseHighlight);
      return this.bind('MouseOut', this.mouseUnhighlight);
    },
    mouseHighlight: function() {
      return this.highlight(15);
    },
    mouseUnhighlight: function() {
      return this.unhighlight(15);
    }
  });
  return key;
});
