// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['Globals', 'Crafty', 'Grid'], function(g, Crafty, Grid) {
  var EditorGrid, blankGrid, editor, key, stageInit, stageUninit;

  blankGrid = function(w, h) {
    var ret, x, y, _i, _ref, _results;

    ret = [];
    _results = [];
    for (x = _i = 0, _ref = w - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
      ret[x] = [];
      _results.push((function() {
        var _j, _ref1, _results1;

        _results1 = [];
        for (y = _j = 0, _ref1 = h - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          _results1.push(ret[x][y] = g.up);
        }
        return _results1;
      })());
    }
    return _results;
  };
  EditorGrid = (function(_super) {
    __extends(EditorGrid, _super);

    function EditorGrid() {
      EditorGrid.__super__.constructor.call(this, blankGrid(4, 4));
      this.showEditorControls();
    }

    EditorGrid.prototype.showEditorControls = function() {};

    return EditorGrid;

  })(Grid);
  editor = null;
  stageInit = function() {
    console.log('loading editor stage');
    return editor = new EditorGrid();
  };
  stageUninit = function() {
    console.log('unloading editor stage');
    return editor.destroy();
  };
  key = 'Editor';
  Crafty.scene(key, stageInit, stageUninit);
  return key;
});
