// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['Globals', 'Crafty', 'Grid', 'ColorScheme', 'components/Highlighter'], function(g, Crafty, Grid, Scheme, Highlighter) {
  var Play, initScene, key, play, uninitScene;

  Play = (function() {
    function Play() {
      this.Victory = __bind(this.Victory, this);      this._level = 0;
      this.advanceLevel();
    }

    Play.prototype.destroy = function() {
      return this.grid.destroy();
    };

    Play.prototype.advanceLevel = function() {
      this._level += 1;
      return this.loadLevel();
    };

    Play.prototype.loadLevel = function() {
      this.level = g.levelData[this._level];
      return this.ensureGrid(this.level.data);
    };

    Play.prototype.ensureGrid = function(data) {
      this.grid = new Grid(data);
      return this.grid.bind('Victory', this.Victory);
    };

    Play.prototype.Victory = function(grid) {
      this.grid.destroy();
      return this.advanceLevel();
    };

    return Play;

  })();
  play = null;
  initScene = function() {
    return play = new Play();
  };
  uninitScene = function() {
    play.destroy();
    return play = null;
  };
  key = "Play";
  Crafty.scene(key, initScene, uninitScene);
  return key;
});
