// Generated by CoffeeScript 1.6.2
define(function() {
  var rgb;

  rgb = function(r, g, b) {
    return {
      r: r,
      g: g,
      b: b
    };
  };
  return {
    primary: [rgb(71, 105, 146), rgb(70, 96, 128), rgb(44, 79, 121), rgb(95, 131, 173), rgb(104, 136, 173)],
    secondary: [rgb(223, 201, 98), rgb(195, 178, 100), rgb(184, 162, 61), rgb(231, 211, 118), rgb(231, 213, 131)],
    tertiary: [rgb(223, 130, 98), rgb(195, 124, 100), rgb(184, 92, 61), rgb(231, 147, 118), rgb(231, 156, 131)]
  };
});

/*  Color Palette by Color Scheme Designer
 Palette URL: http://colorschemedesigner.com/#3C320hWs0g0g0
 Color Space: RGB;



*** Primary Color:

var. 1 = #476992 = rgb(71,105,146)
	var. 2 = #466080 = rgb(70,96,128)
	var. 3 = #2C4F79 = rgb(44,79,121)
	var. 4 = #5F83AD = rgb(95,131,173)
	var. 5 = #6888AD = rgb(104,136,173)

*** Secondary Color A:

var. 1 = #DFC962 = rgb(223,201,98)
	var. 2 = #C3B264 = rgb(195,178,100)
	var. 3 = #B8A23D = rgb(184,162,61)
	var. 4 = #E7D376 = rgb(231,211,118)
	var. 5 = #E7D583 = rgb(231,213,131)

*** Secondary Color B:

var. 1 = #DF8262 = rgb(223,130,98)
	var. 2 = #C37C64 = rgb(195,124,100)
	var. 3 = #B85C3D = rgb(184,92,61)
	var. 4 = #E79376 = rgb(231,147,118)
	var. 5 = #E79C83 = rgb(231,156,131)

Generated by Color Scheme Designer (c) Petr Stanicek 2002-2010
*/

