// Generated by CoffeeScript 1.6.2
define(['Crafty', 'Square'], function(Crafty, Square) {
  var Game;

  Game = {
    start: function() {
      Crafty.init(480, 640);
      return Crafty.background('green');
    }
  };
  return Game;
});
