// Generated by CoffeeScript 1.6.2
define(['Crafty', 'Grid'], function(Crafty, Grid) {
  var Game;

  Game = {
    start: function() {
      Crafty.init(480, 640);
      Crafty.background('white');
      return new Grid();
    }
  };
  return Game;
});
