// Generated by CoffeeScript 1.6.2
define(['Globals', 'Crafty', 'Grid'], function(g, Crafty, Grid) {
  var LevelStage;

  return LevelStage = (function() {
    function LevelStage(n) {}

    return LevelStage;

  })();
});
