// Generated by CoffeeScript 1.6.2
define(['Crafty', 'components/TweenColor'], function(Crafty, TweenColor) {
  var key;

  key = 'Square';
  Crafty.c(key, {
    init: function() {
      this.requires("2D, Tween, " + TweenColor + ", Canvas, Color, Mouse");
      this.attr({
        x: 10,
        y: 10,
        w: 50,
        h: 50
      });
      this.rgb(0, 0, 0);
      this.bind('MouseOver', this.MouseOver);
      return this.bind('MouseOut', this.MouseOut);
    },
    MouseOver: function() {
      return this.tweenColor({
        r: 255,
        g: 0,
        b: 0
      }, 15);
    },
    MouseOut: function() {
      return this.tweenColor({
        r: 0,
        g: 0,
        b: 0
      }, 15);
    }
  });
  return key;
});
