// Generated by CoffeeScript 1.6.2
define(['Crafty', 'components/Highlighter', 'ColorScheme'], function(Crafty, Highlighter, Scheme) {
  var DEG, DOWN, LEFT, LIMIT, NEXT, RIGHT, UP, key;

  key = 'Square';
  UP = 0;
  RIGHT = 1;
  DOWN = 2;
  LEFT = 3;
  LIMIT = 4;
  DEG = function(dir) {
    return dir * 90;
  };
  NEXT = function(dir) {
    return (dir + 1) % LIMIT;
  };
  Crafty.c(key, {
    init: function() {
      var size;

      size = 50;
      this.requires("2D, Tween, Canvas, Color, Mouse, " + Highlighter);
      this.attr({
        w: size,
        h: size
      });
      this.baseColor(Scheme.primary[0]);
      this.highColor(Scheme.primary[4]);
      this.origin("center");
      this.arrow = Crafty.e("2D, Canvas, Color, Tween, " + Highlighter);
      this.arrow.attr({
        w: 10,
        h: 10
      });
      this.arrow.origin(5, 25);
      this.arrow.shift(20, 0);
      this.arrow.baseColor(Scheme.secondary[0]);
      this.arrow.highColor(Scheme.secondary[4]);
      this.attach(this.arrow);
      this.bind('Click', this.Click);
      this.bind('MouseOver', this.MouseOver);
      return this.bind('MouseOut', this.MouseOut);
    },
    Click: function() {
      var next;

      next = NEXT(this.attr('sqdir'));
      this.attr('sqdir', next);
      return this.tween({
        rotation: next === 0 ? DEG(LIMIT) : DEG(next)
      }, 15);
    },
    MouseOver: function(e) {
      this.highlight(15);
      return this.arrow.highlight(15);
    },
    MouseOut: function(e) {
      this.unhighlight(15);
      return this.arrow.unhighlight(15);
    },
    randomizeDirection: function() {
      var dir;

      dir = ~~(Math.random() * LIMIT);
      this.attr('sqdir', dir);
      return this.rotation = dir * 90;
    }
  });
  return key;
});
